### ISSUE TITLE
Including option for adding class to event

### ISSUE THREAD

**Issue by hieunc229** [konsumer/mithril-calendar#1]
Hi there,

Thanks for a great tiny plugin for mithril I found useful.

I recently ran into a case that need to specify different color highlight for different event, I want to contribute here.

Basiclly, in the library line 32 it was

```
classes += '.event'
```

I would changed it to 

```
var optionClass = events[k].class == undefined ? '' : "."+events[k].class
        classes += '.event'+ optionClass;
```

So when adding event, after specifying the key for it, I added an attribute called "class" the the event as follow example

```
events[ (now.getMonth() + 1) + '/21/' + now.getFullYear()] = m('span', [
            "Event 1 ",
            m('b', 'HTML ok')
        ]);
events[ (now.getMonth() + 1) + '/21/' + now.getFullYear()] .class = 'green'
```

and I have a custom stylesheet that override the 'event' class for example 

```
.calendar .green { background: green !important; }
```

Thanks David for a great plugin

**Comment by konsumer** [comment]
Sounds like a good idea. Happy to accept a pull request!

**Comment by konsumer** [comment]
I couldn't get `class` to pass through, not sure why:

First I made change, as you suggested. Then I setup my event like this:

``` js
events[ (now.getMonth() + 1) + '/23/' + now.getFullYear()] = "Event 3"
events[ (now.getMonth() + 1) + '/23/' + now.getFullYear()].class='test2'
```

I tried `className` too.

**Comment by konsumer** [comment]
This works, but doesn't set the parent class:

``` js
events[ (now.getMonth() + 1) + '/22/' + now.getFullYear()] = m('span.test1', 'Event 2');
```

**Comment by konsumer** [comment]
I think it's because it's only a string. If I do this in the console, I also can't set class:

``` js
> x="tester"
"tester"
> x.class = 'cool'
"cool"
> x.class
undefined
```

So I think String just works that way.

I added support for children that are plain text. objects that look like this: `{children: 'Event 5', class:'test1'}` and mithril elements (so you can do more complex styling.) Since an event is a single item, for calendars with multiple events on a single day, you will still need to do fancier mithril components stuff.

**Comment by konsumer** [comment]
I also added a demo, so you can see an example of what I think you want to accomplish.

**Comment by hieunc229** [comment]
David!

(Sorry that I've been away, I tried to make a pull request but since I've never did that before, I'm unsure how to do it)
Your solution does work well and have more complex option. Thank for it!

**Comment by konsumer** [comment]
No prob! In the future, to make a pull request, just press the "fork" button, and then check out your fork, make changes, push them, then press "pull request" button.

**Comment by hieunc229** [comment]
Thanks a lot David!
